# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-04-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
